//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordplay.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordplay.locale.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Game.
        /// </summary>
        internal static string Menu_Game {
            get {
                return ResourceManager.GetString("Menu/Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _High Scores.
        /// </summary>
        internal static string Menu_HighScores {
            get {
                return ResourceManager.GetString("Menu/HighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Game.
        /// </summary>
        internal static string Menu_NewGame {
            get {
                return ResourceManager.GetString("Menu/NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        internal static string Menu_Preferences {
            get {
                return ResourceManager.GetString("Menu/Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu/Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Shuffle Board.
        /// </summary>
        internal static string Menu_ShuffleBoard {
            get {
                return ResourceManager.GetString("Menu/ShuffleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Word.
        /// </summary>
        internal static string Score_CurrentWord {
            get {
                return ResourceManager.GetString("Score/CurrentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Word.
        /// </summary>
        internal static string Score_HighestWord {
            get {
                return ResourceManager.GetString("Score/HighestWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			You have gotten on the high score,
        ///			please enter your name.
        ///		.
        /// </summary>
        internal static string Score_InHighScore {
            get {
                return ResourceManager.GetString("Score/InHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Word.
        /// </summary>
        internal static string Score_LongestWord {
            get {
                return ResourceManager.GetString("Score/LongestWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Score_None {
            get {
                return ResourceManager.GetString("Score/None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Score_Submit {
            get {
                return ResourceManager.GetString("Score/Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        internal static string Score_TotalScore {
            get {
                return ResourceManager.GetString("Score/TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Words.
        /// </summary>
        internal static string Score_TotalWords {
            get {
                return ResourceManager.GetString("Score/TotalWords", resourceCulture);
            }
        }
    }
}
